version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    build:
      context: ./fintech-bd-docker
      dockerfile: Dockerfile
    container_name: fintech-postgres
    environment:
      POSTGRES_DB: fintech_db
      POSTGRES_USER: fintech_user
      POSTGRES_PASSWORD: fintech_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fintech-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fintech_user -d fintech_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend NestJS
  backend:
    build:
      context: ./fintech-back-docker
      dockerfile: Dockerfile
    container_name: fintech-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: fintech_user
      DB_PASSWORD: fintech_password
      DB_NAME: fintech_db
      PORT: 3000
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fintech-network

  # Frontend React + Vite
  frontend:
    build:
      context: ./fintech-front-docker
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3001
    container_name: fintech-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fintech-network

volumes:
  postgres_data:
    driver: local

networks:
  fintech-network:
    driver: bridge
