apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: fintech
  labels:
    app: frontend
data:
  # Esta URL debe apuntar al ALB del backend o usar el ingress path
  VITE_API_URL: "http://backend:3000"
